name: Notify Discord of Commit

on:
  push:
    branches:
      - '**'

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_MESSAGE=$(jq -r '.commits[0].message' "$GITHUB_EVENT_PATH" | sed ':a;N;$!ba;s/\n/\\n/g')
          COMMIT_AUTHOR=$(jq -r '.commits[0].author.name' "$GITHUB_EVENT_PATH")
          COMMIT_URL=$(jq -r '.commits[0].url' "$GITHUB_EVENT_PATH")
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")

          PAYLOAD=$(jq -n \
            --arg username "GitHub Bot" \
            --arg title "New Commit to '$BRANCH_NAME'" \
            --arg description "$COMMIT_MESSAGE" \
            --arg author "$COMMIT_AUTHOR" \
            --arg branch "$BRANCH_NAME" \
            --arg url "$COMMIT_URL" \
            '{
              username: $username,
              embeds: [{
                title: $title,
                description: $description,
                color: 5814783,
                fields: [
                  { name: "Author", value: $author, inline: true },
                  { name: "Branch", value: $branch, inline: true }
                ],
                url: $url
              }]
            }')

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "$PAYLOAD" \
            "$DISCORD_WEBHOOK"
