name: Notify Discord of Commit

on:
  push:
    branches:
      - '**'

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          SANITIZED_COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | sed ':a;N;$!ba;s/\n/\\n/g')
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Bot",
            "embeds": [{
              "title": "New Commit to '"$BRANCH_NAME"'",
              "description": "'"$SANITIZED_COMMIT_MESSAGE"'",
              "color": 5814783,
              "fields": [
                {
                  "name": "Author",
                  "value": "'"$COMMIT_AUTHOR"'",
                  "inline": true
                },
                {
                  "name": "Branch",
                  "value": "'"$BRANCH_NAME"'",
                  "inline": true
                }
              ],
              "url": "'"$COMMIT_URL"'"
            }]
          }' \
          "$DISCORD_WEBHOOK"
